/**
 * AI Executive Report Generator
 *
 * Produces a rich HTML email report combining live financial data,
 * cached AI analyses (SWOT, valuation, predictions, market) and a
 * fresh AI-written executive narrative.
 */

import { db } from "@workspace/db";
import {
  aiAnalysesTable, aiValuationsTable, aiPredictionsTable, aiMarketAnalysesTable,
  aiReportHistoryTable, transactionsTable, companiesTable,
} from "@workspace/db";
import { eq, desc, and, sql } from "drizzle-orm";
import { getActiveProvider, getActiveProviderName } from "./ai-provider";
import {
  buildCompanyContext, buildPortfolioContext,
  formatContextForPrompt, buildMonthlyFinanceTrend,
} from "./ai-context";
import { appUrl } from "./email";

// ── Helpers ───────────────────────────────────────────────────────────────────
const inr = (n: number | null | undefined) => {
  const v = Number(n ?? 0);
  if (v >= 10_000_000) return `₹${(v / 10_000_000).toFixed(1)}Cr`;
  if (v >= 100_000)    return `₹${(v / 100_000).toFixed(1)}L`;
  return `₹${Math.round(v).toLocaleString("en-IN")}`;
};

const pct = (n: number | null | undefined) => {
  if (n == null) return "—";
  return `${n >= 0 ? "+" : ""}${n.toFixed(1)}%`;
};

const esc = (v: unknown) =>
  String(v ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");

const REPORT_NARRATIVE_SYSTEM = `You are an executive business analyst writing a concise weekly/monthly/quarterly report for the company owner.
Based on the provided financial and operational data, write a 200-300 word executive narrative in professional business language.
Cover: financial health, notable trends, key risks, and the single most important action the owner should take.
Write in third-person. Do NOT use bullet points — write flowing paragraphs.
Return ONLY the narrative text, no headers, no markdown.`;

// ── HTML section builders ─────────────────────────────────────────────────────
function reportLayout(headline: string, date: string, bodyHtml: string): string {
  const url = appUrl();
  const cta = url
    ? `<tr><td style="padding:16px 0 4px;">
         <a href="${esc(url)}/ai-assistant" style="display:inline-block;background:#6d28d9;color:#ffffff;text-decoration:none;padding:12px 24px;border-radius:8px;font-weight:600;font-size:14px;">Open Full Dashboard</a>
       </td></tr>`
    : "";
  return `<!doctype html>
<html><body style="margin:0;background:#0b0b0f;padding:24px;font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;margin:0 auto;background:#15151c;border:1px solid #26262e;border-radius:16px;overflow:hidden;">
  <!-- Header -->
  <tr><td style="padding:24px 28px 18px;border-bottom:1px solid #24242e;">
    <div style="display:flex;justify-content:space-between;align-items:center;">
      <span style="color:#a78bfa;font-size:20px;font-weight:700;letter-spacing:-0.02em;">TapasHub</span>
      <span style="color:#6b7280;font-size:12px;">Business OS · AI Executive Report</span>
    </div>
    <h1 style="margin:10px 0 4px;color:#f4f4f5;font-size:22px;">${esc(headline)}</h1>
    <div style="color:#6b7280;font-size:12px;">${esc(date)}</div>
  </td></tr>
  <!-- Body -->
  <tr><td style="padding:24px 28px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="color:#cbd5e1;font-size:14px;line-height:1.6;">
      ${bodyHtml}
      ${cta}
    </table>
  </td></tr>
  <!-- Footer -->
  <tr><td style="padding:16px 28px;border-top:1px solid #24242e;color:#6b7280;font-size:11px;line-height:1.5;">
    This report was automatically generated by TapasHub AI. All AI-generated figures are estimates and should not be treated as official financial statements. To manage report schedules, visit your TapasHub settings.
  </td></tr>
</table>
</body></html>`;
}

function kpiRow(items: { label: string; value: string; delta?: string; color?: string }[]): string {
  const cells = items.map(({ label, value, delta, color }) => `
    <td style="padding:12px;background:#1e1e2a;border-radius:8px;text-align:center;width:${Math.floor(100 / items.length)}%;">
      <div style="color:#6b7280;font-size:11px;margin-bottom:4px;">${esc(label)}</div>
      <div style="color:${color ?? "#f4f4f5"};font-size:18px;font-weight:700;">${esc(value)}</div>
      ${delta ? `<div style="color:${delta.startsWith("+") ? "#34d399" : "#f87171"};font-size:11px;margin-top:2px;">${esc(delta)}</div>` : ""}
    </td>`).join('<td style="width:8px;"></td>');
  return `<tr><td style="padding:0 0 16px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr>${cells}</tr></table>
  </td></tr>`;
}

function sectionHeader(title: string, emoji = ""): string {
  return `<tr><td style="padding:16px 0 8px;">
    <div style="color:#a78bfa;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;border-bottom:1px solid #24242e;padding-bottom:6px;">${emoji ? esc(emoji) + " " : ""}${esc(title)}</div>
  </td></tr>`;
}

function bulletList(items: string[], color = "#6b7280"): string {
  if (!items.length) return "";
  return `<tr><td style="padding:0 0 12px;">
    <ul style="margin:0;padding-left:18px;color:${color};">
      ${items.slice(0, 4).map(i => `<li style="margin-bottom:4px;">${esc(i)}</li>`).join("")}
    </ul>
  </td></tr>`;
}

function paragraph(text: string): string {
  return `<tr><td style="padding:0 0 16px;color:#cbd5e1;line-height:1.7;">${esc(text)}</td></tr>`;
}

function twoCol(left: { label: string; items: string[]; color?: string }, right: { label: string; items: string[]; color?: string }): string {
  const col = (label: string, items: string[], color = "#6b7280") =>
    `<td style="width:48%;vertical-align:top;background:#1e1e2a;border-radius:8px;padding:12px;">
      <div style="color:#9ca3af;font-size:11px;font-weight:600;margin-bottom:8px;">${esc(label)}</div>
      <ul style="margin:0;padding-left:16px;color:${color};font-size:13px;">
        ${items.slice(0, 3).map(i => `<li style="margin-bottom:3px;">${esc(i)}</li>`).join("")}
      </ul>
    </td>`;
  return `<tr><td style="padding:0 0 12px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr>
      ${col(left.label, left.items, left.color ?? "#6b7280")}
      <td style="width:4%;"></td>
      ${col(right.label, right.items, right.color ?? "#6b7280")}
    </tr></table>
  </td></tr>`;
}

// ── Main entry point ──────────────────────────────────────────────────────────

export interface GenerateReportOptions {
  companyId:      number | null;  // null = portfolio-wide
  type:           string;         // weekly | monthly | quarterly | manual
  recipientEmails: string[];
  scheduleId?:    number;
}

export interface GeneratedReport {
  subject:    string;
  htmlContent: string;
  aiSummary:  string;
}

export async function generateExecutiveReport(opts: GenerateReportOptions): Promise<GeneratedReport> {
  const { companyId, type } = opts;

  // ── 1. Resolve company / portfolio name ────────────────────────────────────
  let reportTitle: string;
  let companyName: string;

  if (companyId != null) {
    const [co] = await db.select({ name: companiesTable.name, industry: companiesTable.industry })
      .from(companiesTable).where(eq(companiesTable.id, companyId)).limit(1);
    companyName = co?.name ?? `Company #${companyId}`;
    reportTitle = companyName;
  } else {
    companyName = "Portfolio";
    reportTitle = "Group Portfolio";
  }

  const typeLabel = { weekly: "Weekly", monthly: "Monthly", quarterly: "Quarterly", manual: "Executive" }[type] ?? "Executive";
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const subject = `${typeLabel} Executive Report — ${reportTitle} — ${now.toLocaleDateString("en-IN", { month: "short", year: "numeric" })}`;

  // ── 2. Fetch live financial snapshot ───────────────────────────────────────
  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
  const startStr = `${startOfMonth.getFullYear()}-${String(startOfMonth.getMonth() + 1).padStart(2, "0")}-01`;
  const endStr   = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;

  let mtdRevenue = 0, mtdExpenses = 0;
  if (companyId != null) {
    const [fin] = await db.select({
      income:   sql<number>`coalesce(sum(case when type='income'  then amount else 0 end),0)`,
      expenses: sql<number>`coalesce(sum(case when type='expense' then amount else 0 end),0)`,
    }).from(transactionsTable)
      .where(and(eq(transactionsTable.companyId, companyId), sql`date >= ${startStr}`, sql`date <= ${endStr}`));
    mtdRevenue   = Number(fin?.income   ?? 0);
    mtdExpenses  = Number(fin?.expenses ?? 0);
  }

  // ── 3. Fetch cached AI analyses ────────────────────────────────────────────
  let swot: typeof aiAnalysesTable.$inferSelect | null = null;
  let valuation: typeof aiValuationsTable.$inferSelect | null = null;
  let predictions: typeof aiPredictionsTable.$inferSelect | null = null;
  let market: typeof aiMarketAnalysesTable.$inferSelect | null = null;

  if (companyId != null) {
    const [s] = await db.select().from(aiAnalysesTable)
      .where(eq(aiAnalysesTable.companyId, companyId)).orderBy(desc(aiAnalysesTable.createdAt)).limit(1);
    swot = s ?? null;

    const [v] = await db.select().from(aiValuationsTable)
      .where(eq(aiValuationsTable.companyId, companyId)).orderBy(desc(aiValuationsTable.createdAt)).limit(1);
    valuation = v ?? null;

    const [p] = await db.select().from(aiPredictionsTable)
      .where(eq(aiPredictionsTable.companyId, companyId)).orderBy(desc(aiPredictionsTable.createdAt)).limit(1);
    predictions = p ?? null;

    const [m] = await db.select().from(aiMarketAnalysesTable)
      .where(eq(aiMarketAnalysesTable.companyId, companyId)).orderBy(desc(aiMarketAnalysesTable.createdAt)).limit(1);
    market = m ?? null;
  }

  // ── 4. Fetch trend + context for narrative ─────────────────────────────────
  let contextText = "";
  const trend = companyId != null
    ? await buildMonthlyFinanceTrend(companyId, 3)
    : [];

  if (companyId != null) {
    const ctx = await buildCompanyContext(companyId);
    if (ctx) contextText = formatContextForPrompt(ctx);
  } else {
    const pCtx = await buildPortfolioContext(undefined);
    if (pCtx) contextText = formatContextForPrompt(pCtx as unknown as Parameters<typeof formatContextForPrompt>[0]);
  }

  // ── 5. Generate AI executive narrative ────────────────────────────────────
  const provider = await getActiveProvider();
  const providerName = await getActiveProviderName();

  let trendSnippet = "";
  if (trend.length) {
    trendSnippet = trend.map(t => `${t.month}: Rev ${inr(t.revenue)} | Exp ${inr(t.expenses)} | Profit ${inr(t.profit)}`).join("; ");
  }

  const narrativeInput = [
    companyId != null ? `Company: ${companyName}` : `Portfolio report`,
    `Report type: ${typeLabel}`,
    `Period: ${dateStr}`,
    contextText ? `\nBusiness data:\n${contextText}` : "",
    trendSnippet ? `\nRecent 3-month trend: ${trendSnippet}` : "",
    valuation ? `\nAI Valuation: ${inr(valuation.estimatedValue)} estimated value, ${valuation.healthTrend} trend, growth score ${valuation.growthScore}/100` : "",
    swot?.summary ? `\nSWOT summary: ${swot.summary}` : "",
    market?.recommendations.length
      ? `\nTop recommendation: ${market.recommendations[0]?.title}` : "",
  ].filter(Boolean).join("\n");

  let aiNarrative = "";
  try {
    aiNarrative = await provider.chat(
      [{ role: "user", content: narrativeInput }],
      REPORT_NARRATIVE_SYSTEM,
    );
    // Strip any markdown artefacts
    aiNarrative = aiNarrative.replace(/^#+\s*/gm, "").trim();
  } catch {
    aiNarrative = `AI narrative generation failed. Please run a manual analysis from the TapasHub dashboard to get current insights.`;
  }

  // ── 6. Assemble HTML ───────────────────────────────────────────────────────
  let bodyHtml = "";

  // Financial snapshot
  const mtdProfit = mtdRevenue - mtdExpenses;
  if (companyId != null) {
    bodyHtml += sectionHeader(`${typeLabel} Financial Snapshot`, "📊");
    bodyHtml += kpiRow([
      { label: "MTD Revenue",  value: inr(mtdRevenue),  color: "#34d399" },
      { label: "MTD Expenses", value: inr(mtdExpenses), color: "#f87171" },
      { label: "MTD Profit",   value: inr(mtdProfit),   color: mtdProfit >= 0 ? "#34d399" : "#f87171" },
    ]);
  }

  // AI Valuation widget
  if (valuation) {
    bodyHtml += sectionHeader("Business Valuation (AI Estimate)", "💎");
    bodyHtml += kpiRow([
      { label: "Est. Company Value",  value: inr(valuation.estimatedValue),  color: "#a78bfa" },
      { label: "Growth Score",        value: `${valuation.growthScore ?? "—"}/100`,
        color: (valuation.growthScore ?? 0) >= 70 ? "#34d399" : (valuation.growthScore ?? 0) >= 40 ? "#fbbf24" : "#f87171" },
      { label: "Health Trend",        value: valuation.healthTrend ?? "—",
        color: valuation.healthTrend === "growing" ? "#34d399" : valuation.healthTrend === "declining" ? "#f87171" : "#fbbf24" },
    ]);
    if (valuation.explanation) bodyHtml += paragraph(valuation.explanation);
  }

  // SWOT highlights
  if (swot) {
    bodyHtml += sectionHeader("SWOT Highlights", "🔍");
    bodyHtml += twoCol(
      { label: "Top Strengths",     items: swot.strengths,    color: "#34d399" },
      { label: "Top Opportunities", items: swot.opportunities, color: "#60a5fa" },
    );
    bodyHtml += twoCol(
      { label: "Weaknesses to Address", items: swot.weaknesses, color: "#fbbf24" },
      { label: "Risks to Watch",        items: swot.threats,    color: "#f87171" },
    );
  }

  // Growth predictions (12-month revenue + profit)
  if (predictions?.predictions?.length) {
    const rev12 = predictions.predictions.find(p => p.metric === "revenue"  && p.horizon === 12);
    const pft12 = predictions.predictions.find(p => p.metric === "profit"   && p.horizon === 12);
    const rev6  = predictions.predictions.find(p => p.metric === "revenue"  && p.horizon === 6);
    const pft6  = predictions.predictions.find(p => p.metric === "profit"   && p.horizon === 6);
    if (rev12 || pft12) {
      bodyHtml += sectionHeader("AI Growth Predictions (AI Estimate)", "📈");
      const predKpis = [
        rev6  ? { label: "Revenue (6mo)",  value: inr(rev6.value),  color: "#34d399" } : null,
        rev12 ? { label: "Revenue (12mo)", value: inr(rev12.value), color: "#34d399" } : null,
        pft6  ? { label: "Profit (6mo)",   value: inr(pft6!.value), color: "#a78bfa" } : null,
        pft12 ? { label: "Profit (12mo)",  value: inr(pft12.value), color: "#a78bfa" } : null,
      ].filter((x): x is NonNullable<typeof x> => x !== null).slice(0, 4);
      if (predKpis.length) bodyHtml += kpiRow(predKpis);
    }
  }

  // Market recommendations
  if (market?.recommendations?.length) {
    const sorted = [...market.recommendations].sort(
      (a, b) => ["critical","high","medium","low"].indexOf(a.priority) - ["critical","high","medium","low"].indexOf(b.priority)
    );
    bodyHtml += sectionHeader("Market & Competitive Recommendations", "🎯");
    bodyHtml += bulletList(sorted.slice(0, 4).map(r => `[${r.priority.toUpperCase()}] ${r.title} — ${r.description}`), "#cbd5e1");
  }

  // Revenue leaks & growth opportunities
  if (swot && (swot.revenueleaks.length || swot.growthOpportunities.length)) {
    bodyHtml += sectionHeader("Revenue & Growth Intelligence", "⚡");
    bodyHtml += twoCol(
      { label: "Revenue Leaks",        items: swot.revenueleaks,       color: "#f87171" },
      { label: "Growth Opportunities", items: swot.growthOpportunities, color: "#34d399" },
    );
  }

  // AI narrative
  bodyHtml += sectionHeader("Executive AI Analysis", "🤖");
  bodyHtml += paragraph(aiNarrative);

  // Disclaimer
  bodyHtml += `<tr><td style="padding:12px;background:#1e1e2a;border-radius:8px;font-size:11px;color:#6b7280;line-height:1.5;">
    ⚠️ All AI-generated valuations and forecasts are estimates based on data available in TapasHub. They are not official financial statements and should not be used for legal or accounting purposes. Revenue, profit, and expense figures reflect data entered into TapasHub and may not capture all transactions.
  </td></tr>`;

  const htmlContent = reportLayout(
    `${typeLabel} Executive Report — ${reportTitle}`,
    dateStr,
    bodyHtml,
  );

  void providerName; // used in future: could be added to footer

  return { subject, htmlContent, aiSummary: aiNarrative };
}

// ── Compute next delivery time for a schedule type ────────────────────────────
export function computeNextRunAt(type: string, from = new Date()): Date {
  const d = new Date(from);
  switch (type) {
    case "weekly": {
      // Next Monday at 08:00 IST (02:30 UTC)
      const daysUntilMonday = (8 - d.getDay()) % 7 || 7;
      d.setDate(d.getDate() + daysUntilMonday);
      d.setUTCHours(2, 30, 0, 0);
      return d;
    }
    case "monthly": {
      // First day of next month at 08:00 IST
      d.setMonth(d.getMonth() + 1, 1);
      d.setUTCHours(2, 30, 0, 0);
      return d;
    }
    case "quarterly": {
      // First day of next quarter
      const q = Math.floor(d.getMonth() / 3);
      d.setMonth((q + 1) * 3, 1);
      d.setUTCHours(2, 30, 0, 0);
      return d;
    }
    default:
      return new Date(d.getTime() + 7 * 24 * 60 * 60 * 1000); // 1 week
  }
}

// ── Store a report record ─────────────────────────────────────────────────────
export async function storeReport(opts: {
  companyId: number | null;
  scheduleId?: number;
  type: string;
  status: string;
  subject: string;
  htmlContent?: string;
  aiSummary?: string;
  recipientCount?: number;
  errorMessage?: string;
  sentAt?: Date;
}): Promise<number> {
  const [row] = await db.insert(aiReportHistoryTable).values({
    companyId:      opts.companyId,
    scheduleId:     opts.scheduleId,
    type:           opts.type,
    status:         opts.status,
    subject:        opts.subject,
    htmlContent:    opts.htmlContent,
    aiSummary:      opts.aiSummary,
    recipientCount: opts.recipientCount ?? 0,
    errorMessage:   opts.errorMessage,
    sentAt:         opts.sentAt,
  }).returning({ id: aiReportHistoryTable.id });
  return row.id;
}
