import { Router, type IRouter } from "express";
import { requireAuth } from "../middleware/auth";
import healthRouter from "./health";
import authRouter from "./auth";
import companiesRouter from "./companies";
import dashboardRouter from "./dashboard";
import analyticsRouter from "./analytics";
import ordersRouter from "./orders";
import inventoryRouter from "./inventory";
import financeRouter from "./finance";
import fundAllocationsRouter from "./fund-allocations";
import shareholdersRouter from "./shareholders";
import employeesRouter from "./employees";
import crmRouter from "./crm";
import notificationsRouter from "./notifications";
import approvalsRouter from "./approvals";
import aiRouter from "./ai";
import geminiRouter from "./gemini";
import usersRouter from "./users";
import rolesRouter from "./roles";
import auditRouter from "./audit";
import directorRouter from "./director";
import integrationsRouter from "./integrations";
import accountDirectoryRouter from "./account-directory";
import shippingRouter from "./shipping";
import documentsRouter from "./documents";
import marketingRouter from "./marketing";
import searchRouter from "./search";
import storageRouter from "./storage";
import browserRouter from "./browser";
import treasuryRouter from "./treasury";
import reportsRouter from "./reports";
import aiTasksRouter from "./ai-tasks";
import adminRouter from "./admin";
import aiProductsRouter from "./ai-products";
import connectRouter from "./connect";

const router: IRouter = Router();

// Public (no auth required)
router.use(healthRouter);
router.use(authRouter);

// All other routes require a valid session cookie
router.use(requireAuth);
router.use(companiesRouter);
router.use(dashboardRouter);
router.use(analyticsRouter);
router.use(ordersRouter);
router.use(inventoryRouter);
router.use(financeRouter);
router.use(fundAllocationsRouter);
router.use(shareholdersRouter);
router.use(employeesRouter);
router.use(crmRouter);
router.use(notificationsRouter);
router.use(approvalsRouter);
router.use(aiRouter);
router.use(geminiRouter);
router.use(reportsRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(auditRouter);
router.use(directorRouter);
router.use(integrationsRouter);
router.use(accountDirectoryRouter);
router.use(shippingRouter);
router.use(documentsRouter);
router.use(marketingRouter);
router.use(searchRouter);
router.use(storageRouter);
router.use(browserRouter);
router.use(treasuryRouter);
router.use(aiTasksRouter);
router.use(adminRouter);
router.use(aiProductsRouter);
router.use(connectRouter);

export default router;
